Feature/event view layout
VerxuSs/MealTogether pull request #9
Opened 2024-03-11 09:35 UTC by luaroncrew

2024-03-11 10:04 UTC, luaroncrew commented
Allez defonce moi sur mes competences react

2024-03-12 23:00 UTC, stupside requested changes

2024-03-12 23:00 UTC, stupside commented on apps/frontend/package.json
> +    "@fortawesome/react-fontawesome": "^0.2.0",
heroicons ca suffit pas ? T'ajoute beaucoup de dependances kiki 👎🏽

2024-03-12 23:00 UTC, stupside commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +                        </svg>
Les SVG custom tu peux les mettre dans un composants si tu veux pas surchager le fichier et pour faciliter la relecture.

2024-03-12 23:00 UTC, stupside commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +              <div>
```suggestion
              <div key={menu.id}>
```

Attention quand tu fais un ".map" pour render un element, il faut pas oublié l'attribut "key" pour eviter les rerender.

2024-03-12 23:00 UTC, stupside commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +import { faWheatAlt } from '@fortawesome/free-solid-svg-icons'
Dommage les dependances la 👎🏽

2024-03-12 23:00 UTC, stupside commented on apps/frontend/app/root.tsx
> +    <html lang="en" className="bg-zinc-50">
sur le body ca plutot !

2024-03-12 23:00 UTC, stupside commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +                  <div className="h-10 w-80 border-t-0 flex flex-row justify-start items-center m-0 p-0">
Oublie pas l'attribue "key" quand tu utilise un map pour render des elements

2024-03-14 14:14 UTC, luaroncrew commented on apps/frontend/package.json
> +    "@fortawesome/react-fontawesome": "^0.2.0",
j'en ai besoin

2024-03-14 15:34 UTC, luaroncrew commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +                        </svg>
c'est fait

2024-03-14 15:45 UTC, luaroncrew commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +              <div>
done

2024-03-14 15:49 UTC, luaroncrew commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +import { faWheatAlt } from '@fortawesome/free-solid-svg-icons'
Bonjour Kilian,

Je vois que tu as pris le temps de laisser un commentaire. Cependant, je pense que tu pourrais faire un effort pour rendre tes critiques moins désagréables. Je suis ouvert aux suggestions constructives, mais les remarques acerbes ne sont pas vraiment nécessaires ici.

Bien à vous,
Kirill

2024-03-14 15:53 UTC, stupside commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +import { faWheatAlt } from '@fortawesome/free-solid-svg-icons'
Ne prends pas cela personnellement. En effet, si tu avais pris le temps de lire les dépendances du projet que j'ai décrites dans le fichier Readme, tu aurais remarqué que nous avons déjà une bibliothèque permettant l'ajout d'icônes, de même que pour le tooltip.

Je t'invite à le consulter.

Bien à vous,

Monsieur Kilian.

2024-03-14 16:02 UTC, luaroncrew commented on apps/frontend/app/root.tsx
> +    <html lang="en" className="bg-zinc-50">
done

2024-03-14 16:02 UTC, luaroncrew commented on apps/frontend/app/routes/events+/$id+/_index.tsx
> +                  <div className="h-10 w-80 border-t-0 flex flex-row justify-start items-center m-0 p-0">
done

2024-03-14 16:04 UTC, luaroncrew commented
Ah, même si tes retours en revue ne sont pas tout à fait au top, je dois avouer que ta pull review était plutôt cool. Tes contributions sont appréciées malgré tout !

2024-03-14 16:07 UTC, merged